# Generated by Django 4.2.2 on 2023-08-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productbrand_alter_product_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/brands', verbose_name='تصویر برند'),
        ),
    ]
